gazebo-web/gzweb

src/gzgamepad.js

Signed-off-by: Nate Koenig <nate@openrobotics.org>
Adds a gamepad interface to gz3d. Usage example:
```
var gamepad = new GZ3D.Gamepad(this.onButton, this.onAxes);
private onButton(button: any): void {
console.log('On Button Press', button);
}
private onAxes(axes: any): void {
console.log('On axes', axes);
}
```

Added gamepad interface

---

src/gzgamepad.js

This is so that downstream consumers can, at their option,
get all of the data associated with a gamepad when a button
changes.  This is especially useful when trying to generate
e.g. ROS 2 sensor_msgs/msg/Joy messages, which expect the
complete state of all buttons and axes to be published on
every change.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

Add a controller as the first object to the gamepad callbacks.

---

src/gzgamepad.js

It turns out that gamepad axes are not truly paired, at least,
not along even/odd pairs.  That is, on my gamepad here, the
left analog left/right is axis 0, and the left analog front/back
is axis 1.  But my right analog left/right is axis 3, and the
right analog front/back is axis 4.  So we shouldn't treat these
as pairs, instead just treat them all as individual axes.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

Don't treat gamepad axes as pairs.

---

src/FuelServer.ts
src/Globals.ts
src/SDFParser.ts
src/Scene.ts
src/SceneManager.ts
src/Transport.ts

This PR introduces a couple of changes. I highly recommend to check the following commits, instead of the whole diff:
---
- Trim extra spaces that were added to files.
- Refactor `getDescendants`. Commit: 11ecd3b299f2b7f516cdff6ce5bbfb45a06cee2a
- This is a minor change that can be omitted, but I think it's a good thing to raise awareness of.
- Small tweaks to FuelServer to check both `ignitionrobotics` and `gazebosim` URLs. Commit: cda1daa1bf70cf666b97d414c8172ab6be05dc15
- Rewrite `printGraph()` method. Commit: 5f002aae0aa8263e00db274e093efb6e69d5dc54
- Heightmaps. Commit: 59309939bf0443656607815e1389ca8ae1330c0e
- Use `let` and `const` instead of `var`.
- Style updates.
- **Important**: Default values for `blend`. Otherwise, if it's undefined, it fails.
This PR aims to `heightmap`. We …

Heightmap default values and style updates

---

src/Scene.ts

Signed-off-by: Nate Koenig <nate@openrobotics.org>
The `lookforSubmesh` function was always returning a valid object, when it should return 'false` if the submesh was not found. I've modified the function to return a pair `[boolean, obj]`, where the boolean is true when the submesh was found and false otherwise.
I've also update the `loadTexture` function to cache textures.

Fix submesh logic and cache textures

---

include/OrbitControls.js

Signed-off-by: Nate Koenig <nate@openrobotics.org>
There was a small typo in the `OrbitControls` that caused bad orbit behavior.

Fix orbit controls

---

src/Scene.ts

Signed-off-by: Nate Koenig <nate@openrobotics.org>
This layers a shadow material on heightmaps.
.

Support shadows on heightmaps

---

src/SceneManager.ts
src/Topic.ts

This PR exposes topic subscription to clients. This is required for clients to subscribe to custom topics, such as `/speed`.
Currently, `Transport` is a private member of the Scene Manager, so a new method in the Scene Manager is implemented.
Can you ptal @clalancette ?

Expose subscription to topics in Scene Manager

---

package-lock.json
package.json

This PR bumps `gzweb`'s version, as well as updates dependencies.
Proceeding to merge in order to deploy the new version on NPM.

Release 2.0.12-beta.28

---

src/SceneManager.ts
src/Transport.ts

Addresses [GzWeb to communicate simulation status](https://app.asana.com/0/0/1202738194148095/f).
---
The Connection Status is now available as an Observable. This allows clients to subscribe to status changes.
Clients should subscribe to certain topics, such as `/speed`, only when the connection status is "ready", otherwise, the subscription is ignored.
---
Can you ptal @clalancette or @quiquequique ?

Connection Status as an Observable

---

src/Scene.ts
src/SceneManager.ts

This PR makes improvements to the third-person camera support that was merged in #20 .  In particular, it does the following two things:
1. It fixes a nasty bug where we were miscalculating the time between frames, meaning that the camera movement was much shakier than it was before.
2. It allows the user to move the camera while in third-person follow mode, and then will use that new fixed offset for the camera going forward.  This allows users to readjust where they are watching from.
In order to do the first thing, there is a slight revamp of the logic around `requestAnimationFrame` so that we get the timestamp at which the callback was started.
In my testing, with this and https://github.com/osrf/pounce-web/pull/14 applied, this works fairly well.  There is still a small bug where the …

Allow the user to move the third-person camera

---

package-lock.json
package.json

This PR increases the version of `gzweb`, in order to publish into NPM.

Release 2.0.12-beta.29

---

package-lock.json
package.json

This PR updates `gzweb` to `2.0.12 beta30`, in order to publish a version on npm.

Release 2.0.12 beta30

---

src/Scene.ts
src/SceneManager.ts

This PR handles the Scene's arguments in an interface. We no longer need to explicitly pass `undefined` to unused arguments.
Note that Interfaces do not have default values. They only provide required and optional fields, and their types. The Scene constructor needs to set those default values accordingly.
Can you ptal @nkoenig ? This was part of the changes related to handling websocket assets, but it's cleaner to have on its own.

Clean Scene constructor's arguments

---

include/ColladaLoader.js
src/Asset.ts
src/Scene.ts
src/Transport.ts
src/WsLoadingManager.ts

This PR solves the issue of keeping track of assets loaded via the websocket server. This is required for clients to have a "loading" behavior available.
---
[Loaders](https://threejs.org/docs/#api/en/loaders/Loader) are in charge of loading, parsing and using any kind of resource. They have a [loading manager](https://threejs.org/docs/#api/en/loaders/managers/LoadingManager), which is usually a default one unless provided.
The Loading Managers are in charge of handling and keeping track of loaded and pending data. Whenever a resource begins to being fetched, it increases the number of total items handled. When an item ends, the number of loaded items increases. Then, when the number of loaded items equals the total, the loading manager considers it has finished. 
Here's the current …

Websocket Loading Manager

---

package-lock.json
package.json

This PR updates `gzweb` to `2.0.12 beta31`, in order to publish a version on `npm`.
Includes:
- https://github.com/gazebo-web/gzweb/pull/32
- https://github.com/gazebo-web/gzweb/pull/33
- https://github.com/gazebo-web/gzweb/pull/34

Release 2.0.12-beta31

---

include/ColladaLoader.js

In the Collada Loader, we were not using the correct `item`. Since it was never marked as done, the websocket loading manager never emitted it's end event.

Collada textures with ws loading manager

---

src/AudioTopic.ts

The problem is that currently, we fetch the asset asynchronously, and only then add it to the map.  That means that if other audio messages come in while we are fetching, we'll fetch the data more than once and then play it more than once.
Instead, this PR changes things so that as soon as we get a request for a new audio asset, we immediately add it to the map, then go fetch it asynchronously.  If other audio messages for the same asset come in, they will just harmlessly try to play audio that isn't there yet.  When we have finished downloading, we replace the object in the map with the fully active one which can be played.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

Fix a problem with multiple audio messages coming in at once.

---

package-lock.json
package.json

This release fixes beta32, which included unwanted changes.
FYI @nkoenig . We need to be careful when running `npm publish`. We need to make sure we've built the changes intended for the release. My build had `debugger` lines when trying the skybox. Sorry for the additional noise.

Release 2.0.12-beta33

---

include/ColladaLoader.js
src/Material.ts
src/SDFParser.ts

This PR applies some minor material and light-related fixes, as well as changing the color space encoding of the Collada Loader.
This achieves the goal of maintaining the visual look of the previous version.
Note: The following screenshots were captured using [this branch of GazeboApp](https://github.com/gazebo-web/gazebosim-app/pull/23). Make sure you use the latest changes of it.
---
See [Color Management at ThreeJS docs](https://threejs.org/docs/#manual/en/introduction/Color-management).
The Collada Loader used to have an encoding of `sRGBEncoding`, which replaced the original `LinearEncoding`. This caused our models to look different between our `gzweb` versions. This PR restores back the encoding to `LinearEncoding`.
- Make `ambient`, `diffuse` and `specular` in `Material` to be …

Gzweb2 - Collada Color space and other fixes

---

package-lock.json
package.json
src/SceneManager.ts

The `SceneManager` hid any lights from models. With this PR, now we make it to show lights by default.
A config can be sent to the `SceneManager` constructor if we don't want this behaviour (`new SceneManager({ enableLights: false })`)
Can you ptal @nkoenig ? This also includes a version bump (`2.0.14`)

SceneManager - Enable lights by default

---

src/SDFParser.ts
src/Scene.ts
src/SpawnModel.ts

This adds support for `cone`, `capsule`, and `ellipsoid`. 
Here it is shown with `shapes.sdf` :

Add missing primitive model support
